name: Sync Documents

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: self-hosted

    steps:
      - name: Checkout Documentation Repository
        uses: actions/checkout@v4

      - name: Clone Hospitality Repository
        run: |
          git clone --branch main https://x-access-token:${{ secrets.PAT_TOCKEN }}@github.com/bizinternal/hospitality.git production

      - name: Debug Workspace
        run: |
          echo "========================"
          echo "Current Working Directory"
          echo "========================"
          pwd

          echo ""
          echo "========================"
          echo "Workspace"
          echo "========================"
          ls -lah

          echo ""
          echo "========================"
          echo "Source Documents"
          echo "========================"
          ls -lah docs

          echo ""
          echo "========================"
          echo "Production Repository"
          echo "========================"
          ls -lah production

          echo ""
          echo "========================"
          echo "Production Documents"
          echo "========================"
          ls -lah production/documents

      - name: Copy Documents
        working-directory: ${{ github.workspace }}
        run: |
          echo "Removing old documents..."
          rm -rf production/documents/*

          echo "Copying new documents..."
          cp -rv docs/. production/documents/

          echo "After Copy"
          ls -lah production/documents

      - name: Commit and Push Changes
        working-directory: ${{ github.workspace }}/production
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add documents

          if git diff --cached --quiet; then
            echo "No changes detected."
            exit 0
          fi

          git commit -m "Auto sync documents from documents repository"

          git push origin main
